# Docs:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - azurepipeline
    
variables:
  terraformVersion: 0.12.29
  agentPool: 'ubuntu-18.04'

stages:
  - stage: PlanInfra
    jobs:
      - job: Validate
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: ${{ variables.terraformVersion }}
      - template: pipeline-templates/terraform-plan.yaml
        parameters:
          environment: 'sandbox'
          service_connection: 'azurerm-sandbox'
          storage_account_rg: 'mgmt-state-store-sandbox'
          storage_account_name: 'mgmtstatestoresandbox'
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}

      - job: Archive
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'

  - stage: ApplySandbox
    dependsOn: GetArtifacts
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: pipeline-templates/terraform-apply.yaml
        parameters:
          environment: 'sandbox'
          service_connection: 'azurerm-sandbox'
          storage_account_rg: 'mgmt-state-store-sandbox'
          storage_account_name: 'mgmtstatestoresandbox'
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}
